### ISSUE TITLE
Not parsing config directory

### ISSUE THREAD

**Issue by cristobal23** [cristobal23/zeus#1]
##### Issue Type:

Bug Report
##### Zeus Version:

zeus==0.1.0
##### Environment:

OSX 10.11.2
Running cement==2.6.2
Python 2.7.11
##### Summary:

Adding a key value pair to config/plugin.d/example.conf does not become addressable to the example plugin controller.
##### Steps To Reproduce:

```
zeus example example-plugin-command
```
##### Expected Results:

```
Inside ExamplePluginController.example_plugin_command()
thunderbolt
```
##### Actual Results:

``` python
Inside ExamplePluginController.example_plugin_command()
Traceback (most recent call last):
  File "/Users/cris/.virtualenvs/zeus/bin/zeus", line 9, in <module>
    load_entry_point('zeus==0.1.0', 'console_scripts', 'zeus')()
  File "/Users/cris/code/zeus/zeus/cli/main.py", line 57, in main
    app.run()
  File "/Users/cris/.virtualenvs/zeus/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/Users/cris/.virtualenvs/zeus/lib/python2.7/site-packages/cement/core/controller.py", line 466, in _dispatch
    return func()
  File "/Users/cris/.virtualenvs/zeus/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/cris/code/zeus/zeus/cli/plugins/example.py", line 43, in example_plugin_command
    print self.app.config.get('example', 'symbol')
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'example'
```

**Comment by derks** [comment]
This is due to the fact that the `example` plugin is not enabled.  By default, a Cement app looks for plugin configurations in: `/etc/yourapp/plugins.d`:
- https://github.com/cristobal23/zeus/blob/master/zeus/cli/main.py#L13

And `plugins` themselves are searched for in `/var/lib/yourapp/plugins` (external from your code) **or** tries to load them from `yourapp.cli.plugins` (shipped with your code):
- https://github.com/cristobal23/zeus/blob/master/zeus/cli/main.py#L16
- https://github.com/cristobal23/zeus/blob/master/zeus/cli/main.py#L31

I saw that you hard-coded the `ExamplePluginController` in your `zeus.cli.bootstrap`.  You don't want to do this unless you explicitly need your app to rely on that plugin (where the user can't enable/disable it).  in order to load a plugin, you simply need to enable it from a plugin config file.  In the `boss:cement-app` template, the example plugin is included and an example config is included in `yourapp/config/plugins.d/example.conf`.  However, the `yourapp/config` directory is **not** searched for configuration files by default.  

Cement apps looks for config files in the following locations (by default):
- `/etc/yourapp/yourapp.conf`
- `~/.yourapp.conf`
- `~/.yourapp/config`

In development, I always add a config file at `~/.myapp.conf` or `~/.myapp/config` and override the default `plugin_config_dir`.  In this case, I added the following for `zeus`:

**~/.zeus.conf**:

```
[zeus]
plugin_config_dir = /Users/derks/Development/zeus/config/plugins.d
```

And also removed the `ExamplePluginController` from `zeus.cli.bootstrap` (otherwise you will get errors that the example plugin is already loaded):

```
(zeus)derks-mac [zeus] $ zeus example example-plugin-command
Inside ExamplePluginController.example_plugin_command()
thunderbolt
```

**Comment by cristobal23** [comment]
Indeed, after merging your pull request #2 to remove the hardcoded example plugin from `zeus/cli/bootstrap.py` and adding to my `~/.zeus.conf`:

``` ini
[zeus]
plugin_config_dir = /Users/cris/code/zeus/config/plugins.d
```

I too was able to get the expected results:

``` shellsession
$ zeus example example-plugin-command
Inside ExamplePluginController.example_plugin_command()
thunderbolt
```
